..\game.exe: game.obj efp.obj ipx.obj error.obj int.obj midas.lib rgbhsl.obj globvar.obj miscfunc.obj fade.obj draw.obj write.obj classes.obj rout.obj newfuncs.obj options.obj
	wlink @tk.lnk

options.obj: options.cpp globvar.h types.h defines.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c options.cpp
newfuncs.obj: newfuncs.cpp globvar.h types.h defines.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c newfuncs.cpp
rout.obj: rout.cpp globvar.h types.h defines.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c rout.cpp
classes.obj: classes.cpp globvar.h types.h defines.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c classes.cpp
write.obj: write.cpp globvar.h types.h defines.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c write.cpp
fade.obj: fade.cpp globvar.h types.h defines.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c fade.cpp
draw.obj: draw.cpp draw.h types.h globvar.h defines.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c draw.cpp
miscfunc.obj: miscfunc.cpp miscfunc.h types.h globvar.h defines.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c miscfunc.cpp
globvar.obj: globvar.cpp globvar.h defines.h types.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c globvar.cpp
rgbhsl.obj: rgbhsl.c rgbhsl.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c rgbhsl.c
error.obj: error\error.cpp error\error.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c error\error.cpp
game.obj: game.cpp efp\efp.h error\error.h ipx/ipx.h defines.h types.h globvar.h miscfunc.h newfuncs.h options.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c game.cpp
ipx.obj: ipx/ipx.cpp ipx/ipx.h int/int.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c ipx\ipx.cpp
efp.obj: efp\efp.cpp efp\efp.h error\error.h
	wcl386 -oneatx -zp4 -5r -7 -fp5 -wx /c efp\efp.cpp
